Sponsorship Page
HackRU/Sponsorship pull request #2
Opened 2019-01-13 23:27 UTC by dhruvilp

Ready to Merge?

2019-01-14 10:28 UTC, thekabistro requested changes
Hey @dhruvilp! Great job so far with this!   I have just a couple comments.  I pushed a commit that properly ignores the `node_modules` folder.  It doesn't need to be included in the repo. 

- There seem to be some CSS issues. 
  - It seems that the HackRU logo isn't centered on larger screens.  <img width="1340" alt="screen shot 2019-01-14 at 3 48 38 pm" src="https://user-images.githubusercontent.com/5863372/51107381-afd69900-1814-11e9-91e5-1ae93cd3e96f.png">
  - It also seems to look weird on mobile devices
  - On mobile devices it seems that some of the text is running off of the page.  This is particularly important for the packages sections.  Our finance team wants to be able to pull this up on their phones so we definitely need this to look good. 

Once those get resolved I think we'll be able to push live :) Let me know if anything else needs clarification.

2019-01-14 10:28 UTC, thekabistro commented on frontend/public/index.html
> -    <link rel="shortcut icon" href="%PUBLIC_URL%/assets/fav.png">
Is there a reason why you removed `%PUBLIC_URL%`? We'll need this when we push to live I believe.

2019-01-14 10:28 UTC, thekabistro commented on frontend/src/MLHBadge.jsx
> +            <a id="mlh-trust-badge" style={{ display: "block", visibility: "visible", maxWidth: "100px", minWidth: "60px", position: "absolute", right: "50px", top: "0", width: "10%", zIndex: "10" }}
Is this needed?

2019-01-14 10:28 UTC, thekabistro commented on readme.md
> -
Any particular reason to remove all this?  I figure it might be useful for someone down the line.

2019-01-14 14:44 UTC, dhruvilp commented on frontend/public/index.html
> -    <link rel="shortcut icon" href="%PUBLIC_URL%/assets/fav.png">
I couldn't get the new favicon so I changed it to this one. Is there a way to update the old one?

2019-01-14 14:45 UTC, dhruvilp commented on frontend/src/MLHBadge.jsx
> +            <a id="mlh-trust-badge" style={{ display: "block", visibility: "visible", maxWidth: "100px", minWidth: "60px", position: "absolute", right: "50px", top: "0", width: "10%", zIndex: "10" }}
no, I was trying to make it visible on all the sections of the page but not needed!

2019-01-14 14:46 UTC, dhruvilp commented on readme.md
> -
Well, I didn't make any changes to the Readme file. I don't know who removed it!

2019-01-14 14:47 UTC, dhruvilp commented
yeah, I'll fix those CSS issues.

2019-01-14 17:48 UTC, thekabistro commented on frontend/src/MLHBadge.jsx
> +            <a id="mlh-trust-badge" style={{ display: "block", visibility: "visible", maxWidth: "100px", minWidth: "60px", position: "absolute", right: "50px", top: "0", width: "10%", zIndex: "10" }}
Ah.  I intentionally got rid of that lol.  If you want it back, make it `display: "absolute"`.

2019-01-14 23:10 UTC, dhruvilp commented on frontend/public/index.html
> -    <link rel="shortcut icon" href="%PUBLIC_URL%/assets/fav.png">
i fixed it!

2019-01-14 23:23 UTC, dhruvilp commented
Good to go!!!

2019-01-16 14:07 UTC, thekabistro commented
@dhruvilp 
<img width="964" alt="screen shot 2019-01-16 at 9 06 35 am" src="https://user-images.githubusercontent.com/5863372/51254055-24711b00-196e-11e9-8fbd-2a866a906fa3.png">

Looks like a 1024 width results in this :\

2019-01-16 14:08 UTC, thekabistro commented
We should also and get the testimonials in the page as actual text and not images, but we can do this later.

2019-01-16 14:13 UTC, dhruvilp commented
> @dhruvilp
> <img alt="screen shot 2019-01-16 at 9 06 35 am" width="964" src="https://user-images.githubusercontent.com/5863372/51254055-24711b00-196e-11e9-8fbd-2a866a906fa3.png">
> 
> Looks like a 1024 width results in this :\

Ok, I can fix this and also look into testimonials as well.

2019-01-18 03:06 UTC, thekabistro commented
This looks really good!! There still seems to be a slight margin on the right side of the page whenever the mobile view is invoked.  We're almost ready to push!

2019-01-18 05:21 UTC, thekabistro requested changes

2019-01-18 05:21 UTC, thekabistro commented on frontend/src/components/Sponsorship/Sections/Recap.jsx
> +                        <h4 class="zoom">575 <i class="fa fa-caret-up gold fa-sm"></i></h4><div><h3>Totol Hackers</h3></div>
Oops. Slight typo here.  Totolly missed it.

2019-01-19 23:45 UTC, thekabistro approved these changes

2019-01-20 15:34 UTC, merged